spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
            - id: user-service-docs
              uri: lb://user-service
              predicates:
                - Path=/docs/user-service
              filters:
                - RewritePath=/docs/user-service, /v3/api-docs

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://192.168.10.46:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /docs/user-service
